import Head from "next/head";
import { useSearchMembersByFilterQuery } from "api/membersApi";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data, isLoading } = useSearchMembersByFilterQuery();
  console.log(data, isLoading, "daata");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
